export interface Strings {
  title: string;
  toggle: string;
  drop: string;
  select: string;
  uploading: string;
  completed: string;
  failed: string;
  files: string;
  refresh: string;
  delete: string;
  restore: string;
  close: string;
  showList: string;
  hideList: string;
  empty: string;
  size: string;
  created: string;
  actions: string;
  copy: string;
  copied: string;
  errorCopy: string;
  movedToTrash: string;
}

export const STRINGS: Record<string, Strings> = {
  en: {
    title: 'File uploader',
    toggle: '⇪',
    drop: 'Drop files here or click to browse',
    select: 'Select file',
    uploading: 'Uploading :name',
    completed: 'Upload finished',
    failed: 'Upload failed',
    files: 'Files',
    refresh: 'Refresh',
    delete: 'Delete',
    restore: 'Restore',
    close: 'Close',
    showList: 'Show files',
    hideList: 'Hide files',
    empty: 'No files yet',
    size: 'Size',
    created: 'Created',
    actions: 'Actions',
    copy: 'Copy link',
    copied: 'Link copied',
    errorCopy: 'Unable to copy',
    movedToTrash: 'File moved to trash',
  },
  ru: {
    title: 'Загрузчик файлов',
    toggle: '⇪',
    drop: 'Перетащите файлы сюда или нажмите для выбора',
    select: 'Выбрать файл',
    uploading: 'Загрузка «:name»',
    completed: 'Загрузка завершена',
    failed: 'Ошибка загрузки',
    files: 'Файлы',
    refresh: 'Обновить',
    delete: 'Удалить',
    restore: 'Восстановить',
    close: 'Закрыть',
    showList: 'Показать файлы',
    hideList: 'Скрыть файлы',
    empty: 'Пока нет файлов',
    size: 'Размер',
    created: 'Создан',
    actions: 'Действия',
    copy: 'Копировать ссылку',
    copied: 'Ссылка скопирована',
    errorCopy: 'Не удалось скопировать',
    movedToTrash: 'Файл перемещён в корзину',
  },
  es: {
    title: 'Subidor de archivos',
    toggle: '⇪',
    drop: 'Arrastra archivos aquí o haz clic para explorar',
    select: 'Seleccionar archivo',
    uploading: 'Subiendo :name',
    completed: 'Subida completada',
    failed: 'Error al subir',
    files: 'Archivos',
    refresh: 'Actualizar',
    delete: 'Eliminar',
    restore: 'Restaurar',
    close: 'Cerrar',
    showList: 'Mostrar archivos',
    hideList: 'Ocultar archivos',
    empty: 'No hay archivos todavía',
    size: 'Tamaño',
    created: 'Creado',
    actions: 'Acciones',
    copy: 'Copiar enlace',
    copied: 'Enlace copiado',
    errorCopy: 'No se pudo copiar',
    movedToTrash: 'Archivo movido a la papelera',
  },
  pt: {
    title: 'Envio de arquivos',
    toggle: '⇪',
    drop: 'Arraste arquivos aqui ou clique para procurar',
    select: 'Selecionar arquivo',
    uploading: 'Enviando :name',
    completed: 'Envio concluído',
    failed: 'Falha no envio',
    files: 'Arquivos',
    refresh: 'Atualizar',
    delete: 'Excluir',
    restore: 'Restaurar',
    close: 'Fechar',
    showList: 'Mostrar arquivos',
    hideList: 'Ocultar arquivos',
    empty: 'Nenhum arquivo ainda',
    size: 'Tamanho',
    created: 'Criado em',
    actions: 'Ações',
    copy: 'Copiar link',
    copied: 'Link copiado',
    errorCopy: 'Não foi possível copiar',
    movedToTrash: 'Arquivo movido para a lixeira',
  },
  zh: {
    title: '文件上传',
    toggle: '⇪',
    drop: '将文件拖放至此处，或点击浏览',
    select: '选择文件',
    uploading: '正在上传 :name',
    completed: '上传完成',
    failed: '上传失败',
    files: '文件',
    refresh: '刷新',
    delete: '删除',
    restore: '恢复',
    close: '关闭',
    showList: '显示文件',
    hideList: '隐藏文件',
    empty: '暂无文件',
    size: '大小',
    created: '创建时间',
    actions: '操作',
    copy: '复制链接',
    copied: '链接已复制',
    errorCopy: '复制失败',
    movedToTrash: '文件已移至回收站',
  },
  fr: {
    title: 'Envoi de fichiers',
    toggle: '⇪',
    drop: 'Déposez les fichiers ici ou cliquez pour parcourir',
    select: 'Sélectionner un fichier',
    uploading: 'Envoi de :name',
    completed: 'Envoi terminé',
    failed: "Échec de l'envoi",
    files: 'Fichiers',
    refresh: 'Actualiser',
    delete: 'Supprimer',
    restore: 'Restaurer',
    close: 'Fermer',
    showList: 'Afficher les fichiers',
    hideList: 'Masquer les fichiers',
    empty: 'Aucun fichier pour le moment',
    size: 'Taille',
    created: 'Créé le',
    actions: 'Actions',
    copy: 'Copier le lien',
    copied: 'Lien copié',
    errorCopy: 'Impossible de copier',
    movedToTrash: 'Fichier déplacé dans la corbeille',
  },
  de: {
    title: 'Datei-Upload',
    toggle: '⇪',
    drop: 'Dateien hier ablegen oder klicken zum Durchsuchen',
    select: 'Datei auswählen',
    uploading: ':name wird hochgeladen',
    completed: 'Upload abgeschlossen',
    failed: 'Upload fehlgeschlagen',
    files: 'Dateien',
    refresh: 'Aktualisieren',
    delete: 'Löschen',
    restore: 'Wiederherstellen',
    close: 'Schließen',
    showList: 'Dateien anzeigen',
    hideList: 'Dateien ausblenden',
    empty: 'Noch keine Dateien',
    size: 'Größe',
    created: 'Erstellt',
    actions: 'Aktionen',
    copy: 'Link kopieren',
    copied: 'Link kopiert',
    errorCopy: 'Kopieren nicht möglich',
    movedToTrash: 'Datei in den Papierkorb verschoben',
  },
  sr: {
    title: 'Otpremanje fajlova',
    toggle: '⇪',
    drop: 'Prevucite fajlove ovde ili kliknite za pretragu',
    select: 'Izaberi fajl',
    uploading: 'Otpremanje :name',
    completed: 'Otpremanje završeno',
    failed: 'Otpremanje neuspešno',
    files: 'Fajlovi',
    refresh: 'Osveži',
    delete: 'Obriši',
    restore: 'Vrati',
    close: 'Zatvori',
    showList: 'Prikaži fajlove',
    hideList: 'Sakrij fajlove',
    empty: 'Nema fajlova',
    size: 'Veličina',
    created: 'Kreiran',
    actions: 'Akcije',
    copy: 'Kopiraj link',
    copied: 'Link kopiran',
    errorCopy: 'Kopiranje nije uspelo',
    movedToTrash: 'Fajl premešten u korpu',
  },
};
